ALTER TABLE `catsgotogedog`.`sigtes_information`
    RENAME TO  `catsgotogedog`.`sights_information` ;
ALTER TABLE `catsgotogedog`.`pet_guide`
    CHANGE COLUMN `allowed_pet_type` `allowed_pet_type` VARCHAR(255) NULL DEFAULT NULL ;
ALTER TABLE `catsgotogedog`.`pet_guide`
    CHANGE COLUMN `etc_info` `etc_info` TEXT NULL DEFAULT NULL ;
ALTER TABLE `catsgotogedog`.`recur_information_room`
    CHANGE COLUMN `room_bath_pacility` `room_bath_facility` TINYINT NULL DEFAULT NULL ;
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('1', '서울', '1', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('2', '인천', '2', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('3', '대전', '3', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('4', '대구', '4', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('5', '광주', '5', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('6', '부산', '6', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('7', '울산', '7', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('8', '세종특별자치시', '8', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('9', '경기도', '31', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('10', '강원특별자치도', '32', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('11', '충청북도', '33', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('12', '충청남도', '34', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('13', '경상북도', '35', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('14', '경상남도', '36', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('15', '전북특별자치도', '37', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('16', '전라남도', '38', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sido_code`, `region_level`) VALUES ('17', '제주도', '39', '1');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('18', '강남구', '1', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('19', '강동구', '2', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('20', '강북구', '3', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('21', '강서구', '4', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('22', '관악구', '5', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('23', '광진구', '6', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('24', '구로구', '7', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('25', '금천구', '8', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('26', '노원구', '9', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('27', '도봉구', '10', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('28', '동대문구', '11', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('29', '동작구', '12', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('30', '마포구', '13', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('31', '서대문구', '14', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('32', '서초구', '15', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('33', '성동구', '16', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('34', '성북구', '17', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('35', '송파구', '18', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('36', '양천구', '19', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('37', '영등포구', '20', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('38', '용산구', '21', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('39', '은평구', '22', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('40', '종로구', '23', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('41', '중구', '24', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('42', '중랑구', '25', '1', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('43', '강화군', '1', '2', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('44', '계양구', '2', '2', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('45', '미추홀구', '3', '2', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('46', '남동구', '4', '2', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('47', '동구', '5', '2', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('48', '부평구', '6', '2', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('49', '서구', '7', '2', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('50', '연수구', '8', '2', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('51', '옹진군', '9', '2', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('52', '중구', '10', '2', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('53', '대덕구', '1', '3', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('54', '동구', '2', '3', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('55', '서구', '3', '3', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('56', '유성구', '4', '3', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('57', '중구', '5', '3', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('58', '남구', '1', '4', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('59', '달서구', '2', '4', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('60', '달성군', '3', '4', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('61', '동구', '4', '4', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('62', '북구', '5', '4', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('63', '서구', '6', '4', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('64', '수성구', '7', '4', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('65', '중구', '8', '4', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('66', '군위군', '9', '4', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('67', '광산구', '1', '5', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('68', '남구', '2', '5', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('69', '동구', '3', '5', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('70', '북구', '4', '5', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('71', '서구', '5', '5', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('72', '강서구', '1', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('73', '금정구', '2', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('74', '기장군', '3', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('75', '남구', '4', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('76', '동구', '5', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('77', '동래구', '6', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('78', '부산진구', '7', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('79', '북구', '8', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('80', '사상구', '9', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('81', '사하구', '10', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('82', '서구', '11', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('83', '수영구', '12', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('84', '연제구', '13', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('85', '영도구', '14', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('86', '중구', '15', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('87', '해운대구', '16', '6', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('88', '중구', '1', '7', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('89', '남구', '2', '7', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('90', '동구', '3', '7', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('91', '북구', '4', '7', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('92', '울주군', '5', '7', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('93', '세종특별자치시', '1', '8', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('94', '가평군', '1', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('95', '고양시', '2', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('96', '과천시', '3', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('97', '광명시', '4', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('98', '광주시', '5', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('99', '구리시', '6', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('100', '군포시', '7', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('101', '김포시', '8', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('102', '남양주시', '9', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('103', '동두천시', '10', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('104', '부천시', '11', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('105', '성남시', '12', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('106', '수원시', '13', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('107', '시흥시', '14', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('108', '안산시', '15', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('109', '안성시', '16', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('110', '안양시', '17', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('111', '양주시', '18', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('112', '양평군', '19', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('113', '여주시', '20', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('114', '연천군', '21', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('115', '오산시', '22', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('116', '용인시', '23', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('117', '의왕시', '24', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('118', '의정부시', '25', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('119', '이천시', '26', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('120', '파주시', '27', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('121', '평택시', '28', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('122', '포천시', '29', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('123', '하남시', '30', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('124', '화성시', '31', '31', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('125', '강릉시', '1', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('126', '고성군', '2', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('127', '동해시', '3', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('128', '삼척시', '4', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('129', '속초시', '5', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('130', '양구군', '6', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('131', '양양군', '7', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('132', '영월군', '8', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('133', '원주시', '9', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('134', '인제군', '10', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('135', '정선군', '11', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('136', '철원군', '12', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('137', '춘천시', '13', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('138', '태백시', '14', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('139', '평창군', '15', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('140', '홍천군', '16', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('141', '화천군', '17', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('142', '횡성군', '18', '32', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('143', '괴산군', '1', '33', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('144', '단양군', '2', '33', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('145', '보은군', '3', '33', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('146', '영동군', '4', '33', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('147', '옥천군', '5', '33', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('148', '음성군', '6', '33', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('149', '제천시', '7', '33', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('150', '진천군', '8', '33', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('151', '청주시', '10', '33', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('152', '충주시', '11', '33', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('153', '증평군', '12', '33', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('154', '공주시', '1', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('155', '금산군', '2', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('156', '논산시', '3', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('157', '당진시', '4', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('158', '보령시', '5', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('159', '부여군', '6', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('160', '서산시', '7', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('161', '서천군', '8', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('162', '아산시', '9', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('163', '예산군', '11', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('164', '천안시', '12', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('165', '청양군', '13', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('166', '태안군', '14', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('167', '홍성군', '15', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('168', '계룡시', '16', '34', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('169', '경산시', '1', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('170', '경주시', '2', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('171', '고령군', '3', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('172', '구미시', '4', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('173', '김천시', '6', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('174', '문경시', '7', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('175', '봉화군', '8', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('176', '상주시', '9', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('177', '성주군', '10', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('178', '안동시', '11', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('179', '영덕군', '12', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('180', '영양군', '13', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('181', '영주시', '14', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('182', '영천시', '15', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('183', '예천군', '16', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('184', '울릉군', '17', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('185', '울진군', '18', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('186', '의성군', '19', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('187', '청도군', '20', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('188', '청송군', '21', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('189', '칠곡군', '22', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('190', '포항시', '23', '35', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('191', '거제시', '1', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('192', '거창군', '2', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('193', '고성군', '3', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('194', '김해시', '4', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('195', '남해군', '5', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('196', '밀양시', '7', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('197', '사천시', '8', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('198', '산청군', '9', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('199', '양산시', '10', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('200', '의령군', '12', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('201', '진주시', '13', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('202', '창녕군', '15', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('203', '창원시', '16', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('204', '통영시', '17', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('205', '하동군', '18', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('206', '함안군', '19', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('207', '함양군', '20', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('208', '합천군', '21', '36', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('209', '고창군', '1', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('210', '군산시', '2', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('211', '김제시', '3', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('212', '남원시', '4', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('213', '무주군', '5', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('214', '부안군', '6', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('215', '순창군', '7', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('216', '완주군', '8', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('217', '익산시', '9', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('218', '임실군', '10', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('219', '장수군', '11', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('220', '전주시', '12', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('221', '정읍시', '13', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('222', '진안군', '14', '37', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('223', '강진군', '1', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('224', '고흥군', '2', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('225', '곡성군', '3', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('226', '광양시', '4', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('227', '구례군', '5', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('228', '나주시', '6', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('229', '담양군', '7', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('230', '목포시', '8', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('231', '무안군', '9', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('232', '보성군', '10', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('233', '순천시', '11', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('234', '신안군', '12', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('235', '여수시', '13', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('236', '영광군', '16', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('237', '영암군', '17', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('238', '완도군', '18', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('239', '장성군', '19', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('240', '장흥군', '20', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('241', '진도군', '21', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('242', '함평군', '22', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('243', '해남군', '23', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('244', '화순군', '24', '38', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('245', '남제주군', '1', '39', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('246', '북제주군', '2', '39', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('247', '서귀포시', '3', '39', '2');
INSERT INTO `catsgotogedog`.`region_code` (`region_id`, `region_name`, `sigungu_code`, `parent_code`, `region_level`) VALUES ('248', '제주시', '4', '39', '2');